version: 1.0.{build}
configuration: Release
environment:
  COVERALLS_REPO_TOKEN:
    secure: lkdMT4GVUZRfNVxLm7vkbm+X9zOTC6VJLbhmrbyhtnheHaUhH93L5I0X8VB3/A7K
before_build:
- cmd: nuget restore IuguClient.sln
build:
  project: IuguClient.sln
  verbosity: minimal
after_build:
- ps: >-
    nuget pack src\IuguClient\IuguClientAPI.csproj -IncludeReferencedProjects -Properties Configuration=Release -Build
after_test:
- cmd: >-
    packages\OpenCover.4.5.3723\OpenCover.Console.exe -register:user -filter:"+[*]IuguClientAPI.* -[*]IuguClientAPI.Tests.*" -target:"packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" -targetargs:"/noshadow /domain:single  src\IuguClient.Tests\bin\release\IuguClient.Tests.dll" -output:coverage.xml

    packages\coveralls.io.1.3.2\tools\coveralls.net.exe --opencover coverage.xml
artifacts:
- path: '*.nupkg'
  name: Nuget Package
#deploy:
#- provider: NuGet
#  api_key:
#    secure: 7vxmZE6f+Ike2u8p4FqPagI3Ptf/Ju8cVKyWb6M6BRhQDUl4tLfy+IJZJvft7wyG
#  skip_symbols: false